#!/usr/bin/env bash
# assert-composition.sh — prove the bucket-policy merge semantics the module
# documents are the semantics the pinned provider actually implements.
#
# The claim under test used to be wrong. An earlier revision put caller documents
# in `source_policy_documents` while documenting that reusing a Sid would
# override the built-in statement. Provider 4.8.0 rejects duplicate Sids there
# outright, so that documented path failed at plan time. This fixture exists so
# that cannot regress silently.
#
# WHAT THIS RUNS AGAINST
#
# The module's own policy documents, lifted out of main.tf at runtime — not a
# hand-maintained copy of them. The earlier version of this script rendered a
# mirrored fixture and guarded the mirror with three greps for individual lines,
# which left a real hole: nothing checked that
# `aws_s3_bucket_policy.app_bucket_public_read` consumes the *composed*
# document. Pointing that resource back at the uncomposed
# `app_bucket_public_read.json` would have silently dropped every caller-
# supplied statement — including the security controls this feature exists to
# let consumers add — while all checks stayed green.
#
# So the composition under test is now the module's, byte for byte, and the
# resource's `policy` assignment is asserted directly.
#
# Still not covered: a live `terraform apply` against AWS. That needs a real
# bucket and credentials. Everything between `var.extra_policy_documents` and
# the JSON handed to `aws_s3_bucket_policy.policy` is covered here.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
TFBIN="${TFBIN:-terraform}"
FIX="$HERE/policy-composition"
GEN="$FIX/generated-module.tf"

pass=0; fail=0
ok() { echo "  ✓ $1"; pass=$((pass + 1)); }
no() { echo "  ✗ $1"; fail=$((fail + 1)); }
die() { echo "  ✗✗ $1" >&2; exit 1; }

cleanup() { rm -rf "$FIX/.terraform" "$FIX/.terraform.lock.hcl" "$FIX"/terraform.tfstate* "$FIX"/*.tfvars.json "$GEN"; }
trap cleanup EXIT
cleanup

# ── lifting blocks out of the module ─────────────────────────────────────────
# Print the HCL block whose header matches $2, from its header line until brace
# depth returns to zero. Comments are stripped before counting so prose braces
# cannot skew the depth; the extracted text is emitted with comments intact.
extract_block() {
  awk -v pat="$2" '
    !on && $0 ~ pat { on = 1 }
    on {
      print
      line = $0; sub(/#.*/, "", line)
      depth += gsub(/\{/, "{", line) - gsub(/\}/, "}", line)
      if (depth == 0) exit
    }
  ' "$1"
}

echo "── the fixture IS the module (extracted, not copied) ──"

builtin_block="$(extract_block "$ROOT/main.tf" '^data "aws_iam_policy_document" "app_bucket_public_read"')"
compose_block="$(extract_block "$ROOT/main.tf" '^data "aws_iam_policy_document" "app_bucket"[[:space:]]*\{')"
var_block="$(extract_block "$ROOT/variables.tf" '^variable "extra_policy_documents"')"

# The built-in document also references the private-origin variables now, so the
# fixture has to declare them or the extracted block will not evaluate. They are
# lifted rather than restated for the same reason everything else here is: a
# restatement can drift. This fixture exercises the DEFAULT (public) mode, so
# they simply take their defaults — private mode has its own suite in
# tests/assert-private-origin.sh.
private_var_blocks=""
for pv in private_origin private_origin_allowed_cidrs private_origin_referer_secret; do
  blk="$(extract_block "$ROOT/variables.tf" "^variable \"$pv\"")"
  [ -n "$blk" ] || die "could not find variable $pv in variables.tf"
  private_var_blocks="$private_var_blocks$blk"$'\n\n'
done

[ -n "$builtin_block" ] || die "could not find data.aws_iam_policy_document.app_bucket_public_read in main.tf"
[ -n "$compose_block" ] || die "could not find data.aws_iam_policy_document.app_bucket in main.tf"
[ -n "$var_block" ] || die "could not find variable extra_policy_documents in variables.tf"
ok "extracted the built-in document, the composing document, and the variable"

# The one thing that genuinely cannot be lifted verbatim: the built-in statement
# scopes itself to the bucket this module creates. Substitute the fixture's
# stand-in, and fail loudly if that reference was not there to substitute —
# silently rendering a document scoped to something else would prove nothing.
if ! printf '%s' "$builtin_block" | grep -q 'aws_s3_bucket\.app_bucket\.arn'; then
  die "the built-in document no longer references aws_s3_bucket.app_bucket.arn — the fixture's substitution is stale"
fi
builtin_block="${builtin_block//aws_s3_bucket.app_bucket.arn/var.bucket_arn}"
ok "rewrote the bucket ARN reference to the fixture's stand-in"

{
  echo "# GENERATED by tests/assert-composition.sh from main.tf + variables.tf."
  echo "# Do not edit, and do not commit: it is rewritten on every run so that it"
  echo "# cannot drift from the module the way a hand-copied fixture can."
  echo
  echo "$var_block"
  echo
  echo "$private_var_blocks"
  echo "$builtin_block"
  echo
  echo "$compose_block"
} > "$GEN"

# The composing document must still be wired the way the docs describe, and it
# must read the variable rather than a fixture-local literal.
printf '%s' "$compose_block" | grep -q 'source_policy_documents.*data\.aws_iam_policy_document\.app_bucket_public_read\.json' &&
  ok "module sources its built-in document" ||
  no "module no longer sources its built-in document"
printf '%s' "$compose_block" | grep -q 'override_policy_documents.*var\.extra_policy_documents' &&
  ok "module passes caller documents as OVERRIDES" ||
  no "module no longer passes caller documents via override_policy_documents"

# ── the production path: what the RESOURCE actually applies ──────────────────
# This is the check whose absence let the mirror prove the wrong thing. The
# composed document is worthless if the resource does not consume it.
echo "── the bucket policy resource consumes the composed document ──"

policy_res="$(extract_block "$ROOT/main.tf" '^resource "aws_s3_bucket_policy" "app_bucket_public_read"')"
[ -n "$policy_res" ] || die "could not find resource aws_s3_bucket_policy.app_bucket_public_read in main.tf"

if printf '%s' "$policy_res" | grep -qE '^[[:space:]]*policy[[:space:]]*=[[:space:]]*data\.aws_iam_policy_document\.app_bucket\.json[[:space:]]*$'; then
  ok "policy = data.aws_iam_policy_document.app_bucket.json (the COMPOSED document)"
else
  no "the bucket policy resource does not apply the composed document — caller statements would be dropped"
  printf '%s\n' "$policy_res" | sed 's/^/      /'
fi

# A second policy resource would replace this one's document on the bucket, so
# the composition would be applied and then thrown away.
n_pol="$(grep -cE '^resource "aws_s3_bucket_policy"' "$ROOT/main.tf" || true)"
[ "$n_pol" = 1 ] &&
  ok "exactly one aws_s3_bucket_policy resource in the module" ||
  no "expected exactly one aws_s3_bucket_policy resource, found $n_pol"

# ── render against the pinned provider ───────────────────────────────────────
echo "── render against the pinned provider ──"
cd "$FIX"
"$TFBIN" init -backend=false -input=false > /dev/null

# data sources only; creates nothing, calls no AWS API
apply() { "$TFBIN" apply -auto-approve -input=false "$@" > /dev/null; }
j() { "$TFBIN" output -raw "$1"; }

apply
ver="$("$TFBIN" version -json | jq -r '.provider_selections["registry.terraform.io/hashicorp/aws"] // .provider_selections["registry.opentofu.org/hashicorp/aws"] // "unknown"')"
echo "  · aws provider $ver"
case "$ver" in
  4.8.*) ok "provider matches the module's pin" ;;
  *) no "provider is $ver, expected 4.8.x" ;;
esac

unique_json="$(j unique_sid_json)"
duplicate_json="$(j duplicate_sid_json)"

# Each case re-applies through `var.extra_policy_documents` — the module's real
# public API — instead of through a separately-wired copy of the composition.
with_extras() {
  jq -n --args '{extra_policy_documents: $ARGS.positional}' "$@" > extras.tfvars.json
  apply -var-file=extras.tfvars.json
}

echo "── default: one statement, unchanged meaning ──"
with_extras
d="$(j composed)"
[ "$(printf '%s' "$d" | jq '.Statement | length')" = 1 ] &&
  ok "exactly one statement" || no "expected exactly one statement"
[ "$(printf '%s' "$d" | jq -r '.Statement[0].Sid')" = PublicReadGetObject ] &&
  ok "Sid is PublicReadGetObject" || no "wrong Sid"
[ "$(printf '%s' "$d" | jq -r '.Statement[0].Effect')" = Allow ] &&
  ok "Effect is Allow" || no "wrong Effect"

# With no caller documents the composition must be a no-op over the built-in
# document — not merely "one statement that looks about right".
[ "$(printf '%s' "$d" | jq -S -c .)" = "$(printf '%s' "$(j builtin)" | jq -S -c .)" ] &&
  ok "the default composition is exactly the built-in document" ||
  no "the default composition altered the built-in document"

echo "── unique Sid: appended, built-in untouched ──"
with_extras "$unique_json"
u="$(j composed)"
[ "$(printf '%s' "$u" | jq '.Statement | length')" = 2 ] &&
  ok "two statements" || no "expected two statements, got $(printf '%s' "$u" | jq '.Statement|length')"
printf '%s' "$u" | jq -e '.Statement[] | select(.Sid=="DenyInsecureTransport")' > /dev/null &&
  ok "the caller statement was appended" || no "the caller statement is missing"
printf '%s' "$u" | jq -e '.Statement[] | select(.Sid=="PublicReadGetObject") | select(.Effect=="Allow")' > /dev/null &&
  ok "the built-in statement survives unchanged" || no "the built-in statement was altered"

echo "── duplicate Sid: caller REPLACES the built-in ──"
with_extras "$duplicate_json"
o="$(j composed)"
[ "$(printf '%s' "$o" | jq '.Statement | length')" = 1 ] &&
  ok "still exactly one statement (replaced, not appended)" ||
  no "expected one statement, got $(printf '%s' "$o" | jq '.Statement|length')"
[ "$(printf '%s' "$o" | jq -r '.Statement[0].Effect')" = Deny ] &&
  ok "the caller's Effect (Deny) won" || no "the built-in Allow survived — override did not take effect"

echo "── the default is SEMANTICALLY equivalent, not byte-identical ──"
# The PR previously claimed byte-identity with 1.4.0. It is false, and stating a
# stronger guarantee than holds is how a real incompatibility later gets waved
# through. What actually holds: same meaning, same resource address.
legacy='{"Version":"2012-10-17","Statement":[{"Sid":"PublicReadGetObject","Effect":"Allow","Principal":"*","Action":"s3:GetObject","Resource":"arn:aws:s3:::example.test/*"}]}'
if [ "$(printf '%s' "$d" | jq -S -c .)" = "$(printf '%s' "$legacy" | jq -S -c .)" ]; then
  ok "default is semantically equivalent to the pre-1.5.0 jsonencode output"
else
  no "default is NOT semantically equivalent to pre-1.5.0"
  diff <(printf '%s' "$legacy" | jq -S .) <(printf '%s' "$d" | jq -S .) || true
fi
[ "$d" != "$legacy" ] &&
  ok "and NOT byte-identical — the weaker, true claim is the documented one" ||
  ok "byte-identical too (still fine; the docs claim only equivalence)"

echo
total=$((pass + fail))
[ "$fail" -eq 0 ] && { echo "policy-composition: PASS ($total checks)"; exit 0; }
echo "policy-composition: FAIL ($fail of $total)"; exit 1
