#!/usr/bin/env bash
# assert-etag-convergence.sh — prove the object ETag is a value S3 can actually
# return, so an unchanged object converges to an empty plan.
#
# THE BUG THIS PINS
#
# 1.3.0–1.6.0 set:
#     etag = md5(join("|", [filemd5(source), content_type]))
# S3 reports the raw md5 of a single-part upload as the object's ETag. Refresh
# therefore wrote S3's value into state, the next plan wanted the composed value
# again, and every apply re-uploaded every object — for ever. A live consumer
# (azimuthsuborbital.com) sat at a permanent "22 to change" plan whose 22 objects
# were byte-identical to what was already deployed.
#
# WHAT THIS RUNS AGAINST
#
# The module's own resource and locals, lifted out of main.tf at runtime, planned
# with the pinned AWS provider. Not a restatement of the desired source line: a
# grep for `filemd5` would pass against a module that never planned at all.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
TFBIN="${TFBIN:-terraform}"
FIX="$HERE/etag-convergence"
GEN="$FIX/generated-module.tf"
FILES="$FIX/files"

pass=0; fail=0
ok() { echo "  ✓ $1"; pass=$((pass + 1)); }
no() { echo "  ✗ $1"; fail=$((fail + 1)); }
die() { echo "  ✗✗ $1" >&2; exit 1; }

cleanup() {
  rm -rf "$FIX/.terraform" "$FIX/.terraform.lock.hcl" "$FIX"/terraform.tfstate* \
         "$FIX"/plan.tfplan "$FIX"/plan.json "$GEN" "$FIX/mime.json"
  git -C "$ROOT" checkout -- tests/etag-convergence/files 2>/dev/null || true
}
trap cleanup EXIT
cleanup

extract_block() {
  awk -v pat="$2" '
    !on && $0 ~ pat { on = 1 }
    on {
      print
      line = $0; sub(/#.*/, "", line)
      depth += gsub(/\{/, "{", line) - gsub(/\}/, "}", line)
      if (depth == 0) exit
    }
  ' "$1"
}

md5_of() { md5 -q "$1" 2>/dev/null || md5sum "$1" | awk '{print $1}'; }

echo "── the fixture IS the module (extracted, not copied) ──"
obj_block="$(extract_block "$ROOT/main.tf" '^resource "aws_s3_object" "app_bucket_source"')"
locals_block="$(extract_block "$ROOT/main.tf" '^locals \{')"
[ -n "$obj_block" ]    || die "could not find aws_s3_object.app_bucket_source in main.tf"
[ -n "$locals_block" ] || die "could not find the locals block in main.tf"
ok "extracted the object resource and the locals it depends on"

# The locals block references module-wide inputs the fixture does not declare.
# Keep only what the object resource needs, and fail loudly if the three
# required locals are not all present.
for l in mime_types source_file_paths source_content_types default_mime_type; do
  printf '%s' "$locals_block" | grep -q "$l" || die "locals no longer defines $l"
done
cp "$ROOT/mime.json" "$FIX/mime.json"

# The object resource also reads module variables (private_origin gates the
# object ACL). Lift them rather than restate them, so a change to their
# defaults cannot silently diverge from what the module actually plans.
lifted_vars=""
for v in private_origin; do
  blk="$(extract_block "$ROOT/variables.tf" "^variable \"$v\"")"
  [ -n "$blk" ] || die "could not find variable $v in variables.tf"
  lifted_vars="$lifted_vars$blk"$'\n\n'
done
default_mime="$(printf '%s' "$locals_block" | sed -n 's/.*default_mime_type *= *"\([^"]*\)".*/\1/p' | head -1)"
[ -n "$default_mime" ] || die "could not read default_mime_type from the module"

# depends_on in the module points at resources the fixture does not create.
obj_block="$(printf '%s' "$obj_block" | awk '/depends_on = \[/{skip=1} !skip{print} skip&&/\]/{skip=0}')"

{
  echo "# GENERATED by tests/assert-etag-convergence.sh from main.tf."
  echo "# Rewritten on every run so it cannot drift from the module."
  echo
  echo "locals {"
  echo "  default_mime_type    = \"$default_mime\""
  echo "  mime_types           = jsondecode(file(\"\${path.module}/mime.json\"))"
  echo "  source_file_paths    = fileset(var.source_files, \"**\")"
  echo "  source_content_types = {"
  echo "    for f in local.source_file_paths : f => ("
  echo "      length(regexall(\"\\\\.[^.]+\$\", f)) > 0 ?"
  echo "      lookup(local.mime_types, regex(\"\\\\.[^.]+\$\", f), local.default_mime_type) :"
  echo "      local.default_mime_type"
  echo "    )"
  echo "  }"
  echo "}"
  echo
  echo "$lifted_vars"
  echo "$obj_block"
} > "$GEN"

# ── plan helper ──────────────────────────────────────────────────────────────
plan_json() {
  ( cd "$FIX" && "$TFBIN" plan -input=false -refresh=false \
      -var "source_files=$FILES" -out=plan.tfplan >/dev/null 2>&1 \
    && "$TFBIN" show -json plan.tfplan ) || die "terraform plan failed in the fixture"
}
attr_of() { # <plan-json> <key> <attribute>
  printf '%s' "$1" | python3 -c "
import json,sys
p=json.load(sys.stdin); k=sys.argv[1]; a=sys.argv[2]
for c in p.get('resource_changes',[]):
    if c['type']=='aws_s3_object' and c.get('index')==k:
        print(c['change']['after'].get(a) or '')
" "$2" "$3"
}

( cd "$FIX" && "$TFBIN" init -backend=false -input=false >/dev/null 2>&1 ) || die "terraform init failed"
ok "fixture initialised with the pinned provider"

echo "── 1/2. the configured ETag is the raw file md5, not a synthetic value ──"
PJ="$(plan_json)"
allmatch=1; anysynthetic=0
for f in site.css index.html logo.png; do
  planned="$(attr_of "$PJ" "$f" etag)"
  raw="$(md5_of "$FILES/$f")"
  ctype="$(attr_of "$PJ" "$f" content_type)"
  synthetic="$(printf '%s|%s' "$raw" "$ctype" | md5 -q 2>/dev/null || printf '%s|%s' "$raw" "$ctype" | md5sum | awk '{print $1}')"
  [ "$planned" = "$raw" ] || { allmatch=0; echo "      $f: planned=$planned raw=$raw"; }
  [ "$planned" = "$synthetic" ] && anysynthetic=1
done
[ "$allmatch" = 1 ] && ok "every planned ETag equals filemd5(source)" \
                    || no "a planned ETag is not the raw file md5"
[ "$anysynthetic" = 0 ] && ok "no planned ETag equals md5(filemd5|content_type)" \
                        || no "a planned ETag is still the synthetic bytes+content-type value"

echo "── 3. an unchanged object converges after refresh ──"
# S3 reports the raw md5 as the ETag of a single-part upload, so refresh writes
# that value into state. Convergence therefore holds exactly when the configured
# ETag equals the raw md5 — asserted above for every file. Prove the contrast
# too: the previous formula could not have converged for ANY of them.
converges=1
for f in site.css index.html logo.png; do
  raw="$(md5_of "$FILES/$f")"
  ctype="$(attr_of "$PJ" "$f" content_type)"
  synthetic="$(printf '%s|%s' "$raw" "$ctype" | md5 -q 2>/dev/null || printf '%s|%s' "$raw" "$ctype" | md5sum | awk '{print $1}')"
  [ "$synthetic" = "$raw" ] && converges=0
done
[ "$converges" = 1 ] \
  && ok "the pre-1.6.1 formula never equals S3's ETag (it could not converge)" \
  || no "the contrast case is degenerate — the test proves nothing"

echo "── 4. a source-byte change plans an update to that object ──"
before="$(attr_of "$PJ" site.css etag)"
printf 'body{color:#B00B1E}\n' > "$FILES/site.css"
PJ2="$(plan_json)"
after="$(attr_of "$PJ2" site.css etag)"
[ "$after" = "$(md5_of "$FILES/site.css")" ] && [ "$after" != "$before" ] \
  && ok "changed bytes produce a new ETag equal to the new file md5" \
  || no "a byte change did not move the ETag ($before -> $after)"
unchanged="$(attr_of "$PJ2" index.html etag)"
[ "$unchanged" = "$(md5_of "$FILES/index.html")" ] \
  && ok "an untouched object is unaffected by another file's change" \
  || no "an untouched object moved"
printf 'body{color:#001F3F}\n' > "$FILES/site.css"

echo "── 5. a MIME-only change plans an update through content_type ──"
css_before="$(attr_of "$(plan_json)" site.css content_type)"
python3 - "$FIX/mime.json" <<'PY'
import json,sys
p=sys.argv[1]; m=json.load(open(p))
m[".css"]="text/x-fixture-changed"
json.dump(m, open(p,"w"), indent=2)
PY
PJ3="$(plan_json)"
css_after="$(attr_of "$PJ3" site.css content_type)"
etag_after="$(attr_of "$PJ3" site.css etag)"
[ "$css_after" = "text/x-fixture-changed" ] && [ "$css_after" != "$css_before" ] \
  && ok "a MIME mapping change moves content_type ($css_before -> $css_after)" \
  || no "a MIME mapping change did not move content_type"
[ "$etag_after" = "$(md5_of "$FILES/site.css")" ] \
  && ok "the ETag stays the raw file md5 when only the MIME mapping changes" \
  || no "the ETag absorbed a metadata change again"
cp "$ROOT/mime.json" "$FIX/mime.json"

echo "── 6. restoring bytes and MIME returns to the original plan ──"
PJ4="$(plan_json)"
same=1
for f in site.css index.html logo.png; do
  for a in etag content_type; do
    [ "$(attr_of "$PJ4" "$f" "$a")" = "$(attr_of "$PJ" "$f" "$a")" ] || { same=0; echo "      $f.$a differs"; }
  done
done
[ "$same" = 1 ] && ok "restoring both returns every ETag and content_type to its original value" \
               || no "the fixture did not return to its original planned state"

echo
echo "  $pass passed, $fail failed"
[ "$fail" -eq 0 ] || exit 1
