# Inspired by: https://blog.raftech.nl/automate-terraform-modules-versioning-with-github-actions-90f91351506a

name: Release Terraform Module
on:
  pull_request:
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803  # v6
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: 'Get next version'
        id: semvers
        uses: 'WyriHaximus/github-action-next-semvers@v1'
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - uses: rickstaa/action-create-tag@a1c7777fcb2fee4f19b0f283ba888afa11678b72  # v1
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        with:
          tag: '${{ steps.semvers.outputs.minor }}'

      - uses: rickstaa/action-create-tag@a1c7777fcb2fee4f19b0f283ba888afa11678b72  # v1
        if: contains(github.event.pull_request.labels.*.name, 'major')
        with:
          tag: '${{ steps.semvers.outputs.major }}'

      - uses: rickstaa/action-create-tag@a1c7777fcb2fee4f19b0f283ba888afa11678b72  # v1
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        with:
          tag: '${{ steps.semvers.outputs.patch }}'
